### ISSUE TITLE
i cant loadCanvas,and what viewport？necessary？thx

### ISSUE THREAD

**Issue by purpleRa1nZ** [ArturRod/ecg-dicom-web-viewer#10]
![image](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/51228391/c2d223a8-5927-4a79-a195-a80b041bd169)

**Comment by ArturRod** [comment]
Hi @purpleRa1nZ 
This may be due to a problem of passing the div without id wrong,
If you notice we have to pass the bytearray, a specific name for the divView (this will be an id) and an identifier of that id 0, 1...since there can be several.
It is designed so that with an id of the div it is generated automatically.
Example:
ecgView -> String ID Div.
0 -> It can have multiple views, if nothing happens, it will initialize to 0
let viewer = new $.DicomECGViewer(arrayBuffer, "ecgView", '0');
viewer.loadCanvas();

**Comment by purpleRa1nZ** [comment]
Thank you for your answer！
but i have a div,its id is ecg,unique,The one in the picture is.

class readerEcg,i can getWaveform() and getInfo(),just cant loadCanvas().

**Comment by ArturRod** [comment]
The code is failing you in this part, the div may not turn out well. Recommending to debug and see if any variable is failing.
![image](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/86238895/b3cd2d6f-f87c-4165-8102-a0ca2d7f7903)

**Comment by purpleRa1nZ** [comment]
nice,I understand!thx have a good step!
![image](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/51228391/715769e0-5164-487c-8023-47f59240c61b)

**Comment by purpleRa1nZ** [comment]
thank you very much much! last i maybe loss a canvas element
