### ISSUE TITLE
DICOM metadata is displayed but waveforms fail to load

### ISSUE THREAD

**Issue by arturojain** [ArturRod/ecg-dicom-web-viewer#2]
**Describe the bug**
For the attached DICOM file (anonymized) nothing is displayed.

**To Reproduce**
1. Open attached DICOM file using v2.0.0

**Expected behavior**
The study should be displayed.

**Screenshots**
<img width="1315" alt="Screen Shot 2022-09-10 at 15 20 39" src="https://user-images.githubusercontent.com/5528886/189500524-fc267c60-d19c-4880-88c2-e22c813f420f.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser: Google Chrome
 - Version: 105.0.5195.102

**Additional context**
Attachment 1: https://we.tl/t-kKSg85j2bJ

**Comment by ArturRod** [comment]
Hi @arturojain 
I have found the problem, it is due to this line:
![imagen](https://user-images.githubusercontent.com/86238895/189527112-76207f72-3d60-40ff-9488-18f8335a8043.png)
Since in the formats that I was reading it comes in the format: "Lead I" and in yours it comes only "I"
![imagen](https://user-images.githubusercontent.com/86238895/189527226-8077f141-8934-4233-8f67-051738ff4d9b.png)
Con mi codigo, se hace un split, y claro al no tener espacio en blanco no detecta la entrada de datos.
I will improve the code so that it reads this data correctly regardless of whether it comes in "Lead I" or just "I".
All the best.

**Comment by arturojain** [comment]
Excelente, muchas gracias.

**Comment by arturojain** [comment]
I will take a look at https://github.com/ArturRod/ecg-dicom-web-viewer/blob/2acc53606e6ff38c696b66ba5fa56b10c8c06283/src/draw/DrawECGCanvas.ts#L297 to see if anything comes to mind.

**Comment by ArturRod** [comment]
Hi @arturojain 
Thanks for the contribution, checked that everything works fine and did the merged, now I will compile it for the npm package.
All the best.
