### ISSUE TITLE
DICOMs not showing ECG and error in DrawECGCanvas

### ISSUE THREAD

**Issue by carlos-actualmed** [ArturRod/ecg-dicom-web-viewer#8]
**Describe the bug**
The attached DICOMs do not display anything. Their SOPUIDs are in the 'Currently it works' list.

**To Reproduce**
1. Open attached DICOM file using v2.0.5

**Expected behavior**
The ECG should be displayed 

**Screenshots**
e1:
![e1](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/84970133/5c205751-2f27-4e61-8ddc-9c4f194a357a)
e2:
![e2](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/84970133/a40a076c-dbcc-47e0-b587-86e14715e7e0)
e3:
![e3](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/84970133/0264651b-0162-4f5a-b969-87139fa8c998)
e4:
![e4](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/84970133/c2d23adc-be9e-422e-832a-9401737f8a01)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: Chrome
 - Version 114.0.5735.134

**Additional context**
I found a problem in DrawECGCanvas.ts:314. The 'code' is not correctly sanitized, and the 'name' does not correspond to it. This solves the problem:
            return obj.name.toUpperCase() === code.trim().replace(/\0/g, "").toUpperCase();
![solution](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/84970133/6417b9ca-1be6-4403-bc3c-be464a4c0508)

However, this only solves the problem in files e1 and e4.
https://we.tl/t-6pMiYS1e7T

**Comment by ArturRod** [comment]
Hi @carlos-actualmed 
The problem is caused by reading data, it appears as Lead I (space) Lead II u\0000, Lead v5\x00... (e1, e2)
![image](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/86238895/0f2cbbb7-bb96-4839-b813-7b7d2bbbb8c9)
The second problem is given since the data reading is for 16 bits and these 2 ecgs come from 13 bits.
![image](https://github.com/ArturRod/ecg-dicom-web-viewer/assets/86238895/50a135e3-dd11-4bc1-9c07-ec351b05a99f)
